services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true
    ScyLabs\SogeCommerceBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations,Tests,Kernel.php,Event}'